### ISSUE TITLE
Removing Donation Check

### ISSUE THREAD

**Issue by fkick** [wouterdebie/locast2tuner#102]
With Locast no longer requiring donations, can the account donation check be removed?

**Comment by johnluber** [comment]
Locust just announced they've suspended operations.  Not sure removing the donation check matters much at this point.

**Comment by wouterdebie** [comment]
Yeah. It might take a bit of time, since I'm out of power because of
hurricane Ida.

**Comment by okc** [comment]
Not that it matters for now, but "disable_donation_check = true" in the config file.
