### ISSUE TITLE
Add --logfile

### ISSUE THREAD

**Issue by wouterdebie** [wouterdebie/locast2tuner#12]
Currently locast2tuner only logs to stdout and it would be nice to be able to specify `--logfile` (as locast2dvr has) to log in a specific location as well.

**Comment by Croq360** [comment]
When you add this, if there's an easy way to have different verbosity of logs on what goes to the screen vs what goes to the logs, that'd be helpful.

**Comment by wouterdebie** [comment]
Good points. Let me check if I can set the RUST_BACKTRACE inside the application, because that would make debugging in especially containers much easier. 

I'm pretty sure we can make a distinction in loglevel between what goes to the screen and what ends up in the logfile.

**Comment by wouterdebie** [comment]
Fixed in 66f944d

**Comment by wouterdebie** [comment]
Version 0.1.19 adds support for a log file as well as logging to syslog. The previous implementation was a bit of a hack to not include timestamps when there was no tty, but that seemed not super nice. v0.1.20 removes the `--force_timestamp` option, since I think logging to a file should always include a timestamp and syslog will take care of timestamping itself.

Now the question is if the Docker version and the Ubuntu/RPi version need to start with `--syslog` or not, in order to properly log. @eiddor any idea?

**Comment by eiddor** [comment]
> Now the question is if the Docker version and the Ubuntu/RPi version need to start with --syslog or not, in order to properly log. @eiddor any idea?

Not sure off-hand, but I will test tonight/tomorrow.  You mean starting `locast2tuner` itself with the `--syslog` option, correct?

**Comment by wouterdebie** [comment]
Exactly. For Ubuntu/Debian that probably works. Not so sure about Docker

**Comment by eiddor** [comment]
Oh, Docker - logging to syslog on the host.  That's an interesting one.  I'll do some research.

**Comment by wouterdebie** [comment]
We don't have to. I assume just regular output is fine.

**Comment by eiddor** [comment]
Ok, let me think about this -

It depends on how much you think logging will be needed.  We could always
log inside of the container and then add a troubleshooting guide for users
to either view it inside the container in real time, or to map it to a
volume on the host the same way they do the config file.

**Comment by wouterdebie** [comment]
@eiddor I think it works well right now with just logging to the terminal. There's a way to use syslog, but I don't think that's necessary for now. 

I think adding `--syslog` to the `systemd` service definition makes sense. Maybe even `--quiet --syslog`.

**Comment by eiddor** [comment]
> @eiddor I think it works well right now with just logging to the terminal. There's a way to use syslog, but I don't think that's necessary for now.

I agree - It's easy enough to eliminate `-d` when starting the container to just have the terminal.  That's how I've been doing it so far.  In theory (at least in my mind) the more mature the project gets, the less this will be required.

> I think adding --syslog to the systemd service definition makes sense. Maybe even --quiet --syslog, because that way we don't have to care about if timestamps should be added or not.

It looks like it's trying to log to `/var/run/syslog` instead of `/var/log/syslog`

For the deb package, is logging to syslog something we really want to do by default vs. having a custom log?  Do we not worry about cluttering it up with normal messages?

**Comment by wouterdebie** [comment]
Logging to /var/run/syslog is correct, since it's a named pipe. But maybe
you're right about logging to a different file. Let me see how other
packages do this. I assume most log through syslog, but add an additional
facility.

**Comment by eiddor** [comment]
> Logging to /var/run/syslog is correct, since it's a named pipe

Ahh, ok - that makes sense.  Raspbian isn't too happy about it, though ;-) 

```
Apr 16 00:18:37 raspberrypi locast2tuner[21242]: config selected = /etc/locast2tuner/config
Apr 16 00:18:37 raspberrypi locast2tuner[21242]: thread 'main' panicked at 'Failed to start syslog on `/var/run/syslog`. Error Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/logging.rs:56:21
Apr 16 00:18:37 raspberrypi locast2tuner[21242]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 16 00:18:37 raspberrypi systemd[1]: locast2tuner.service: Main process exited, code=killed, status=6/ABRT
Apr 16 00:18:37 raspberrypi systemd[1]: locast2tuner.service: Failed with result 'signal'.
```

Updating on the Ubuntu VM to test.

**Comment by eiddor** [comment]
Same message with Ubuntu.

**Comment by wouterdebie** [comment]
Ah! I'll test later!

**Comment by eiddor** [comment]
Sounds good!

Note: The reason I asked how necessary this was is because without any logging options, we can always look at journald for the output with `journalctl -u locast2tuner`

**Comment by wouterdebie** [comment]
@eiddor cool! I'll probably have a look tomorrow.. I just released 0.1.23 (currently building, but available in 15 mins or so) with `locast2tuner.service` reverted.

**Comment by wouterdebie** [comment]
@eiddor I just tested this myself on Ubuntu and it seems to work. I went for *not* using syslog for Ubuntu/Debian, but I've added a log directory in `/var/log/locast2tuner` where we log now. Let me know what you experience before I close this ticket.

**Comment by eiddor** [comment]
This works on both Ubuntu and RPi!  Thank you!
