### ISSUE TITLE
Playback errors when binding to 0.0.0.0

### ISSUE THREAD

**Issue by eiddor** [wouterdebie/locast2tuner#16]
So, this is similar to the issue I had with locast2dvr - If I bind to `0.0.0.0`, I can get through the setup, get the XMLTV guide, etc.

But in PMS when I attempt to play a channel, I get this with no output on the console: 

![image](https://user-images.githubusercontent.com/7586731/113629847-97890980-962c-11eb-9f43-c96b06c7c048.png)

Emby using M3U mode results in a spinning circle when I try to play.  Same problem, I assume.

![image](https://user-images.githubusercontent.com/7586731/113631108-9062fb00-962e-11eb-8f5b-3ee743f0b992.png)

Both of these work if I bind directly to my IP.

This is going to pose some challenges in a Docker container since the container IP is (usually) abstracted.  The workaround in Docker would be to run in host networking mode and bind to the host IP, but that's not a great practice generally.

**Comment by wouterdebie** [comment]
Yeah, I see what you mean. What happens is that not only locast2tuner binds to 0.0.0.0, but also communicates this to PMS/Emby in the `/tuner.m3u` or `/lineup.json`, which is obviously not going to work. I might be able to reworks this by setting the IP address to the address the request was received on.

**Comment by eiddor** [comment]
Oh heck, that makes perfect sense - I'm sure it was the same problem in locast2dvr, then.

Once that's fixed and I can test, I should be able to get things tested and work on the Dockerfile.  I just need to find where I left my locast2dvr stuff haha

**Comment by eiddor** [comment]
Though, this may still be an issue in Docker since the container is behind a NAT.  Hmmm...I'll have to test it out when you get it going.

**Comment by wouterdebie** [comment]
@eiddor yeah, it's the same issue with locast2dvr. I used the bind_address all over the place, but that was wrong. I just fixed it for the normal use case. I use the "Host:" http header, so that should work. It basically replies whatever the client sends, so that should work behind NAT as well.. I have one more fix to make and I'll let you know when that's done.

**Comment by wouterdebie** [comment]
@eiddor this should work now.. I explicitly split by `:`, but that would break anything that runs on `:80` or `:443` and ipv6. 

(so, bonus is that --bind_address ::1 works as well)

**Comment by eiddor** [comment]
Nice!  I'll give it a test tonight.  Thanks for jumping on this so quickly.

**Comment by eiddor** [comment]
Works like a charm in both PMS and Emby, @wouterdebie - Thank you!

**Comment by wouterdebie** [comment]
Great! Thanks for testing!
