### ISSUE TITLE
Crashing and Unable to Tune Channels

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2tuner#18]
Ran locast2tuner and it started generating some errors.  I couldn't tune any channel once the errors started happening.  I had "backtrace" set to 1 for more details.  Sorry about no timestamps, but they weren't generated in the output.

Since the log has some personal info in it, I'll send it to you on Emby.

**Comment by wouterdebie** [comment]
Thanks for this! I see where the error comes from. Once in a while
locast2tuner has to log in again to refresh the auth token and this happens
at startup in a synchronous way, but when running login is called from an
asynchronous context.

I think I'll have a solution soon.

**Comment by Croq360** [comment]
Thanks for the update.  Using locast2dvr in the meantime.

**Comment by wouterdebie** [comment]
This should be fixed now. Would you mind testing this?

**Comment by Croq360** [comment]
I got the latest version of the code and am running it.  Seems to be working okay now.
