### ISSUE TITLE
sources.list empty

### ISSUE THREAD

**Issue by detodotv** [wouterdebie/locast2tuner#19]
hello, i am trying to install this using Ubuntu 18, but i have this error

E: Type '<!DOCTYPE' is not known on line 1 in source list /etc/apt/sources.list.d/locast2tuner.list
E: The list of sources could not be read.

this url is empty

https://wouterdebie.github.io/my_ppa/sources.list

any ideas?

thank you!

**Comment by wouterdebie** [comment]
Oops, sorry. That should be "https://wouterdebie.github.io/ppa/sources.list
<https://wouterdebie.github.io/my_ppa/sources.list>". If fixed the readme.
