### ISSUE TITLE
Issue with EPG?

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2tuner#2]
I got things running with this version, but found that only 3 channels in my Plex listings had guide information.  So, then I loaded up the epg.xml page, and got this error:

This page contains the following errors:
error on line 3 at column 657089: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.

However, if I right click on the page and save it, I can't find that "xmlParseEntityRef" anywhere in the epg.xml file.

**Comment by wouterdebie** [comment]
Thanks for testing! Mind sending me your config so I can try to reproduce?

**Comment by Croq360** [comment]
Sure, I'll send it to you over on our Emby chat.

**Comment by Croq360** [comment]
In further investigating, it appears that this entry in one of the programs may be responsible for the error.

        <actor>Dailey & Vincent</actor>

Note the stand alone "&".  That should be "&amp;".
