### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by detodotv** [wouterdebie/locast2tuner#21]
sorry, new in github, i dont know how to post a question.

is possible to avoid the 4 streams limit with locast2tuner?

thank you!

**Comment by wouterdebie** [comment]
What 4 streams limit?

**Comment by detodotv** [comment]
4 streams at same time, locast did not allow you to have more than 4 streams with one account opened at the same time

**Comment by wouterdebie** [comment]
There is no restriction in locast2tuner, but locast might block you. Not
sure.
