### ISSUE TITLE
Expand Emby/PMS configuration documentation

### ISSUE THREAD

**Issue by wouterdebie** [wouterdebie/locast2tuner#26]

**Comment by eiddor** [comment]
> Do you think we should do this in the README or move this to the Wiki perhaps and link in the Wiki? Or maybe add additional markdown files to the repo in a docs/ directory?

I think the project is simple enough that we can just keep a couple of sections in `docs/` as needed.  

"For detailed instructions on integrating with PMS or Emby, see <link to docs/01_integration.md>."

What do you think?

**Comment by wouterdebie** [comment]
Really good point.

**Comment by Croq360** [comment]
I can put together the docs for PMS if no one else is already working on that.

**Comment by eiddor** [comment]
Thanks for the offer, @Croq360!  I'm working on both at the same time to make them consistent.

**Comment by eiddor** [comment]
@Croq360 I'd appreciate if you could have a look at the instructions in PR #28 and let me know if you see any problems.  Thanks!

**Comment by Croq360** [comment]
@eiddor - I think I already added a comment that I reviewed it and everything looked good.  Maybe in the PR itself?  Anyhow, just replicating that comment here.

**Comment by eiddor** [comment]
Yep, I saw that - Thank you!  Just waiting on @wouterdebie to close the issue.

**Comment by wouterdebie** [comment]
Thanks!
