### ISSUE TITLE
Idea - Save Configuration To A File

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2tuner#33]
I think it'd be nice to offer a way to save off the command-line parameters you're running with to a config file.  You could run the program with all your desired options, then add something like "--save_config=filename" to save the configuration.  The resulting config file would have all the config options you set in there (and maybe even add in the commented out default options that weren't overridden).

**Comment by wouterdebie** [comment]
Interesting idea. I rather not add an option for this. However we currently have `/config` as a path, that outputs a JSON. I could add `/config.ini` that outputs a `config.ini` in the proper format that you can download. That way your "save config" command will just be `curl -o new_config.ini http://localhost:6077/config.ini`. What do you think?

**Comment by Croq360** [comment]
Yeah, that's a better option than what I suggested...

**Comment by wouterdebie** [comment]
Cool! I'll implement that later
