### ISSUE TITLE
panicked at 'called `Result::unwrap()

### ISSUE THREAD

**Issue by jonfive** [wouterdebie/locast2tuner#39]
Having a bit of an issue with the application stopping after a day or so of running. 
it's stopping with:

thread 'actix-rt|system:0|arbiter:9' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: MissingTag { tag: "#EXTM3U", input: " " } }', src/http/mod.rs:382:83"

I'm not exactly sure what it's trying to access. Perhaps when it's trying to get new epg data?

Running in docker on unraid.

**Comment by wouterdebie** [comment]
This should be fixed in the latest version and described in d0ab9f2 :) Closing this for now, but let me know if this still happens with the latest version.
