### ISSUE TITLE
response '204 No Content' 

### ISSUE THREAD

**Issue by sgaert** [wouterdebie/locast2tuner#41]
Hello, i try to get it running since a week, but i have no idea anymore. Here is my log:

> Apr 19 20:45:31 locastvm systemd[1]: Started locast2tuner.
Apr 19 20:45:31 locastvm locast2tuner[4052]: config selected = /etc/locast2tuner/config
Apr 19 20:45:31 locastvm locast2tuner[4052]: Apr 19 20:45:31.711 INFO locast2tuner 0.1.28 on Linux 5.4.0-72-generic starting..
Apr 19 20:45:31 locastvm locast2tuner[4052]: Apr 19 20:45:31.711 INFO UUID: bc412c67-e151-4214-ad27-713b9355cf9a
Apr 19 20:45:31 locastvm locast2tuner[4052]: Apr 19 20:45:31.711 INFO Logging in with xxxxx
Apr 19 20:45:31 locastvm locast2tuner[4052]: Apr 19 20:45:31.753 DEBG starting new connection: https://api.locastnet.org/
Apr 19 20:45:31 locastvm locast2tuner[4052]: Apr 19 20:45:31.875 TRCE registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
Apr 19 20:45:32 locastvm locast2tuner[4052]: Apr 19 20:45:32.263 TRCE signal: Want
Apr 19 20:45:32 locastvm locast2tuner[4052]: Apr 19 20:45:32.267 TRCE signal found waiting giver, notifying
Apr 19 20:45:32 locastvm locast2tuner[4052]: Apr 19 20:45:32.268 TRCE poll_want: taker wants!
Apr 19 20:45:32 locastvm locast2tuner[4052]: Apr 19 20:45:32.405 TRCE signal: Want
Apr 19 20:45:32 locastvm locast2tuner[4052]: thread 'Apr 19 20:45:32.406 TRCE signal: Want
Apr 19 20:45:32 locastvm locast2tuner[4052]: Apr 19 20:45:32.406 DEBG response '204 No Content' for https://api.locastnet.org/api/user/login
Apr 19 20:45:32 locastvm locast2tuner[4052]: Apr 19 20:45:32.407 INFO Login succeeded!
Apr 19 20:45:32 locastvm locast2tuner[4052]: main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }'>
Apr 19 20:45:32 locastvm locast2tuner[4052]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 19 20:45:32 locastvm systemd[1]: locast2tuner.service: Main process exited, code=dumped, status=6/ABRT
Apr 19 20:45:32 locastvm systemd[1]: locast2tuner.service: Failed with result 'core-dump'.

**Comment by wouterdebie** [comment]
Hi!

Would you mind running with `--rust_backgrace` and paste the full log here? Do you have an active locast subscription with donation?

**Comment by sgaert** [comment]
I tryed the CURL Post but not return. I also tryed the curl to the URL without the /login, i received an error json as return.

**Comment by wouterdebie** [comment]
Super weird.. Do you have any "strange" characters in your email address? Or something in your password that locast doesn't like? What if you supply a wrong password? This seems to be an issue with your account. I've tried replicating, but I can't seem to get an empty response.

**Comment by sgaert** [comment]
no strange characters in the credentials. i can write what i like in the usere and password, always no responce. Also the line as you wrote create no responce. When i delete the json out of the request I get an error responce.

sgaert@locastvm:/usr/bin$ curl -X POST  https://api.locastnet.org/api/user/login
{"code":500,"message":"There was an error processing your request. It has been logged (ID 4c9d61865cdd60a9)."}

**Comment by wouterdebie** [comment]
Is there a proxy in the way that blocks you from posting data?

**Comment by sgaert** [comment]
Thank you for your input, I got it. It is the geofence of locast, I´m from the outside of the supported area.
If I use a VPN than I receive a token responce in curl.
