### ISSUE TITLE
Stuck "Downloading FCC Facilities" ... (v 0.1.31)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [wouterdebie/locast2tuner#45]
Won't start, see log data below: 
```
config selected = /config/config
May 04 19:46:38.732 INFO locast2tuner 0.1.31 on Linux 5.10.28-Unraid starting..
May 04 19:46:38.732 INFO UUID: 1314e355-1db2-425a-b9fb-ac1a365b2ef3
May 04 19:46:38.732 INFO Logging in with xxx@xxx.com
May 04 19:46:38.911 INFO Login succeeded!
May 04 19:46:39.188 INFO Downloading FCC facilities
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("transition.fcc.gov")), port: None, path: "/ftp/Bureaus/MB/Databases/cdbs/facility.zip", query: None, fragment: None }, source: hyper::Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', src/fcc_facilities.rs:129:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/config/run.bash: line 19: 8 Aborted locast2tuner --config /config/config -b 0.0.0.0 -m -d 8 -r --tuner_count 4
```

**Comment by wouterdebie** [comment]
It seems like the FCC site is having issues. It might be good to ignore errors if we have an older facilities file already.

**Comment by scotte** [comment]
Same issue here - looks like there was a locast2plex issue for this about 3 weeks ago, then it started working again, but now it has once again started happening - for me it started about 3 hours ago.

**Comment by wouterdebie** [comment]
@scotte good points. I'll probably implement this tomorrow. The FCC URL where I download from has given me headaches because of SSL and I'm considering mirroring the FCC database on a different site as well.

**Comment by wouterdebie** [comment]
I quickly mirrored the facilities on GCS, which is at least something. I'll create a proper mirror tomorrow and will implement the recommended items, but 0.1.32 should at least start again.

**Comment by lawrence1986101** [comment]
im Having the Same issue and I Narrowed it down to a few things the older version you were able to manipulate the zip code so let's say you lived in an area that didn't have Locast you could pop in a zip that would think it's from that area... but now the DMA Trigger on local stating you aren't were your suppose to be.... this is really bad when you think about it because I think Locast computer system just triggered now how do I know this is True well real simple just Fire up a VPN and base it out of a location where locast is based out of like Detroit or Chicago and your able to watch what ever you want... also no workaround on unraid also Tryed to route my docker container through a VPN container Still nothing

**Comment by RandomNinjaAtk** [comment]
@wouterdebie Thanks!
@lawrence1986101 I just pushed an update for the Unraid container, check for updates in the next 20 or so minutes and it should have the latest fixes.

**Comment by RandomNinjaAtk** [comment]
I can confirm, after building my new image with the updated software, everything is working again!

Thanks!

**Comment by lawrence1986101** [comment]
Works nowSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: RandomNinjaAtk ***@***.***> Date: 5/5/21  6:32 AM  (GMT-05:00) To: wouterdebie/locast2tuner ***@***.***> Cc: lawrence1986101 ***@***.***>, Mention ***@***.***> Subject: Re: [wouterdebie/locast2tuner] Stuck "Downloading FCC Facilities" ... (v 0.1.31) (#45) 
@wouterdebie Thanks!
@lawrence1986101 I just pushed an update for the Unraid container, check for updates in the next 20 or so minutes and it should have the latest fixes.
***@***.***

**Comment by wouterdebie** [comment]
> @wouterdebie Thanks!
> @lawrence1986101 I just pushed an update for the Unraid container, check for updates in the next 20 or so minutes and it should have the latest fixes. ([RandomNinjaAtk/docker-locast2tuner@fe722f4](https://github.com/RandomNinjaAtk/docker-locast2tuner/commit/fe722f43459208071d7a708a639fe86900c98dd7))

Is there any reason for you not to use the docker image we're already building?

**Comment by wouterdebie** [comment]
@RandomNinjaAtk do you need to rebuild manually every time I upgrade? If so, I wouldn't mind adding your config for a specialized Docker build.

**Comment by lawrence1986101** [comment]
Ninja I was using a older version of the locast docker. I upgraded last time to yours and it didn't work..... it had that fcc bullshitSo who ever touched that and fixed that fcc thank youSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Wouter de Bie ***@***.***> Date: 5/5/21  9:53 AM  (GMT-05:00) To: wouterdebie/locast2tuner ***@***.***> Cc: lawrence1986101 ***@***.***>, Mention ***@***.***> Subject: Re: [wouterdebie/locast2tuner] Stuck "Downloading FCC Facilities" ... (v 0.1.31) (#45) 

@wouterdebie Thanks!
@lawrence1986101 I just pushed an update for the Unraid container, check for updates in the next 20 or so minutes and it should have the latest fixes. ***@***.***)

Is there any reason for you not to use the docker image we're already building?

**Comment by scotte** [comment]
All good here as well. Thanks for the fix @wouterdebie
