### ISSUE TITLE
Enhancement: Support for more retry options on failures & notifications

### ISSUE THREAD

**Issue by sumocomputers** [wouterdebie/locast2tuner#48]
I am on 0.1.33 using Homebrew on macOS.

I have run into certain issues where locast2tuner fails for some reason, and since my Mac Mini is headless I have no idea whether locast2tuner is running or not. And let me tell you, when you can't provide your wife with reliable Jeopardy recordings, life is slightly less sweet.

For example, in my logs down below, I had an issue with my internal PiHole DNS servers briefly, and locast2tuner just bombed out immediately. 

Here is what I am thinking:

- Some sort of option to have locast2tuner retry when it encounters an error. It could be number of retries, a time span, or maybe the option to combine both.

- Some sort of notification mechanism. Ideally when locast2tuner starts and stops. Email is probably a PITA, so maybe something like Pushover, or maybe something even cooler that I don't know about.

- In line with the above, there could be later enhancement with a "heartbeat" added that just sends out a message like "Running", "Stopped", "Starting", for use in something like a live dashboard (I have several iPads throughout the house).

FYI, there are no labels here in GitHub for enhancement, bug, question, etc.

```
May 09 13:35:06.325 INFO Login succeeded!
May 09 13:35:13.209 INFO Loading stations for Cleveland (cache: true, cache timeout: 3600, days: 30)..
May 09 14:32:13.230 INFO Reloading FCC facilities..
May 09 14:35:13.141 INFO Login token expired: Mutex { is_locked: true, has_waiters: false }
May 09 14:35:13.142 INFO Logging in with myobfuscatedemail@something.com
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.locastnet.org")), port: None, path: "/api/dma", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" })) }', src/fcc_facilities.rs:112:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort trap: 6
```

**Comment by Croq360** [comment]
FWIW, the Windows Service solution I'm currently using has some restart parameters set too.

**Comment by eiddor** [comment]
Agreed with that approach both for full process restart and especially for notifications.  I know @wouterdebie has added some retry behavior/error handling inside of the app itself and I'm sure that's always a WIP.

**Comment by sumocomputers** [comment]
I am using HomeBrew on macOS. I hear you on not wanting to reinvent the wheel.

For at least the restart functionality, would the article linked/Ubuntu apply to macOS via HomeBrew?

If not, I guess I could look at Docker, though I have never really done anything with it. The HomeBrew method seemed very easy and comfortable to me, so I just stuck with it.

**Comment by eiddor** [comment]
So, I haven't tried the HomeBrew version yet and I'm not really sure how it operates, but I wonder if you can run it as a service as in this guide:

https://thoughtbot.com/blog/starting-and-stopping-background-services-with-homebrew

Docker is easy, too, FWIW.  I think you have some options.

**Comment by sumocomputers** [comment]
> So, I haven't tried the HomeBrew version yet and I'm not really sure how it operates, but I wonder if you can run it as a service as in this guide:
> 
> https://thoughtbot.com/blog/starting-and-stopping-background-services-with-homebrew
> 
> Docker is easy, too, FWIW. I think you have some options.

Thanks for the info. I think I will try to get a Docker version up and running; sounds like it opens up a lot of options

**Comment by eiddor** [comment]
I don't want to clutter this issue up anymore, so feel free to ping me directly!
