### ISSUE TITLE
New issue 5/20/2021

### ISSUE THREAD

**Issue by lawrence1986101** [wouterdebie/locast2tuner#53]
my OS is unraid well unraid said it had an update now it will not pull the File 

TOTAL DATA PULLED: 0 B
   
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='locast2tuner' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'L2DUSER'='lawrence.crandall@yahoo.com' -e 'L2DPASS'='BadDodge1986' -e 'L2DZIP'='48202' -p '6077:6077/tcp' 'randomninjaatk/locast2tuner'
Unable to find image 'randomninjaatk/locast2tuner:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for localhost.localdomain, not registry-1.docker.io.
See 'docker run --help'.

The command failed.

**Comment by wouterdebie** [comment]
This issue belongs here: https://github.com/RandomNinjaAtk/docker-locast2tuner/issues. I don't maintain the unraid image.

**Comment by lawrence1986101** [comment]
ok Np
    On Thursday, May 20, 2021, 06:52:09 PM EDT, Wouter de Bie ***@***.***> wrote:  
 
 


This issue belongs here: https://github.com/RandomNinjaAtk/docker-locast2tuner/issues. I don't maintain the unraid image.

**Comment by wouterdebie** [comment]
Also, I don't think that @RandomNinjaAtk actually publishes the image, but I'm not 100% sure. So you'd have to build it before you can run it.

**Comment by eiddor** [comment]
@lawrence1986101 You might want to change your password now.

**Comment by lawrence1986101** [comment]
Ya I will Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Roddie Hasan ***@***.***> Date: 5/20/21  7:15 PM  (GMT-05:00) To: wouterdebie/locast2tuner ***@***.***> Cc: lawrence1986101 ***@***.***>, Mention ***@***.***> Subject: Re: [wouterdebie/locast2tuner] New issue 5/20/2021 (#53) 
@lawrence1986101 You might want to change your password now.

**Comment by wouterdebie** [comment]
I edited your first post and removed your password as well..

**Comment by lawrence1986101** [comment]
thank you i wasn't paying any attention 
    On Friday, May 21, 2021, 02:48:17 PM EDT, Wouter de Bie ***@***.***> wrote:  
 
 


I edited your first post and removed your password as well..
