### ISSUE TITLE
Device Not Found in Plex (But Still Working)

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2tuner#57]
I went into settings in Plex to disable a couple of channels, but when I got there, I saw this for my TV tuner (the port number of 6188 is correct):

![image](https://user-images.githubusercontent.com/25014870/119416042-a17fce00-bca7-11eb-97a5-151e78133232.png)

Interestingly, everything still works fine - I can watch live TV and record stuff, and the guide is up to date and goes out the correct number of days.

**Comment by wouterdebie** [comment]
I don't know how Plex checks for the device being there or not, but I
assume it's by using 65001/UDP, something locast2tuner doesn't do.. let's
keep this on the back burner for now.

**Comment by Croq360** [comment]
What's odd though is that when I initially configured it, the Tuner showed up fine.  Why would it work some times and not other times?

**Comment by eiddor** [comment]
@Croq360 I've had the same problem here for a while - It works fine, but I have that message.

![image](https://user-images.githubusercontent.com/7586731/119426124-48776080-bcce-11eb-8936-0653d13147b9.png)

Funny enough I just restarted Plex to see if it would fix it, and Plex upgraded itself so the UI is a bit different from the above screenshot.  Same issue, though.

![image](https://user-images.githubusercontent.com/7586731/119426715-57aade00-bccf-11eb-972a-1b15e06f16b1.png)

**Comment by Croq360** [comment]
Hmm, I'm not on that version, and Plex thinks I have the latest version.  Maybe that's the "beta" channel or something?  Anyhow, not the end of the world.  I should be able to just update my remap.json file to mark the channel as inactive.  Just not sure if I'm going to have to delete and reload the DVR/tuner device in order to get the channels to go away.

**Comment by wouterdebie** [comment]
> Hmm, I'm not on that version, and Plex thinks I have the latest version. Maybe that's the "beta" channel or something? Anyhow, not the end of the world. I should be able to just update my remap.json file to mark the channel as inactive. Just not sure if I'm going to have to delete and reload the DVR/tuner device in order to get the channels to go away.

Afaik, plex reloads the lineup.json on a regular basis, which should allow for updating your channel remap without having to remove and add the tuner..

**Comment by Croq360** [comment]
So, with the recent changes to the Live TV stuff in Plex, I deleted and recreated my tuner just as before (though this time I used Plex's ability to map their listings to my channel numbers).  And you get more days worth of listings that way too.  It's still showing up (and it's been a few weeks), so I'm going to close this issue.
