### ISSUE TITLE
Error code -9806 connection closed via error

### ISSUE THREAD

**Issue by sumocomputers** [wouterdebie/locast2tuner#58]
Not sure what the cause of this error is, but it just bombed out...

```
May 24 00:27:28.447 DEBG starting new connection: https://api.locastnet.org/
May 24 00:27:29.204 DEBG response '200 OK' for https://api.locastnet.org/api/watch/epg/510?startTime=2021-05-24T00:00:00-00:00&hours=208
May 24 00:27:34.656 INFO Loading stations for Cleveland (cache: true, cache timeout: 3600, days: 30)..
May 24 01:16:35.953 INFO Reloading FCC facilities..
May 24 01:16:35.953 DEBG starting new connection: https://api.locastnet.org/
May 24 01:17:55.508 DEBG response '200 OK' for https://api.locastnet.org/api/dma
May 24 01:17:55.508 INFO Using cached FCC facilities at /Users/mediamacmini/.locast2tuner/facilities
May 24 01:27:34.791 INFO Login token expired: Mutex { is_locked: true, has_waiters: false }
May 24 01:27:34.791 INFO Logging in with *****@gmail.com
May 24 01:27:34.791 DEBG starting new connection: https://api.locastnet.org/
May 24 01:27:35.314 DEBG response '200 OK' for https://api.locastnet.org/api/user/login
May 24 01:27:35.314 INFO Login succeeded!
May 24 01:27:35.314 DEBG starting new connection: https://api.locastnet.org/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.locastnet.org")), port: None, path: "/api/watch/epg/510", query: Some("startTime=2021-05-24T00:00:00-00:00&hours=208"), fragment: None }, source: hyper::Error(Connect, Error { code: -9806, message: "connection closed via error" }) }', src/utils.rs:44:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort trap: 6
```

**Comment by wouterdebie** [comment]
This looks like another transient error that shouldn't break locast2dvr. I'd be curious to see where exactly this happened (i.e. the backtrace). Can you reproduce the error?

**Comment by sumocomputers** [comment]
I think this happened once or twice before, but I can't repro this.

If I turn logging to max, will that do the job if it fails again?

In the meantime, I am running Docker container in parallel as a backup to Plex (and Plex just announced today that they support multiple zip codes & EPGs when you have multiple tuners).

I am off to try it out!

**Comment by wouterdebie** [comment]
Great! any extra logging will help. I want to see what actual call resulted in the issue.

**Comment by sumocomputers** [comment]
I have trace logging on, and will update if I see it again

**Comment by wouterdebie** [comment]
I made a stupid mistake that kept us from retrying when HTTP occur.. I pushed a change and 0.1.41 is now building. Should be there soon. @sumocomputers would you mind testing that version?

**Comment by sumocomputers** [comment]
I will get it installed, keep trace logging on, and report if I see any issues.

**Comment by sumocomputers** [comment]
I had this running for a few days, and never saw the issue come back. I think it should be OK to close it now.

**Comment by wouterdebie** [comment]
@sumocomputers great! Thanks for checking back in!
