### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by wouterdebie** [wouterdebie/locast2tuner#6]
This project could use some more code and user documentation

**Comment by eiddor** [comment]
Once I can get this going in PMS and Emby, I'll add some more color and screenshots to the docs for the basics.

**Comment by eiddor** [comment]
Also need to document the config file format, which will come in handy for Docker.

**Comment by wouterdebie** [comment]
This issues seems to be way too broad to be actionable, closing this..
