### ISSUE TITLE
Donation expired! Make sure you have an active donation at locast.org!

### ISSUE THREAD

**Issue by MapGuy11** [wouterdebie/locast2tuner#61]
I am having this issue with all of these locast2plex dockers. I can confirm I don't need to see ads on Locast and my streams don't disconnect after 15mins either.
My look on Locast.org: [https://i.imgur.com/4gMtPRz.png](url)

**Comment by wouterdebie** [comment]
Do you pay locast every month? The API returns that you don't have an active donation going..

**Comment by MapGuy11** [comment]
Yes, I have had this problem where it will work beautifully in locast.org, but the API returns that I don't have a sub though will serve me a URL that doesn't have ads or disconnect after 15mins.

**Comment by wouterdebie** [comment]
I'm afraid there isn't much we can do about this..
