### ISSUE TITLE
Still getting issues :(

### ISSUE THREAD

**Issue by teleflix** [wouterdebie/locast2tuner#64]
Hello

ok Finally i install Ubuntu 20.04 and this time i install script step by step using this guide

Ubuntu/Debian packages are available for both amd64 and arm7 (Raspbian):

# Add the PPA key
$ curl -s "https://wouterdebie.github.io/ppa/KEY.gpg" | sudo apt-key add -
# Add the locast2tuner repository
$ sudo curl -o /etc/apt/sources.list.d/locast2tuner.list "https://wouterdebie.github.io/ppa/sources.list"
$ sudo apt update
# Install locast2tuner
$ sudo apt install locast2tuner
Create a config file. Don't forget to edit the config file!

$ sudo cp /etc/locast2tuner/config.example /etc/locast2tuner/config
# Edit the config file
$ nano /etc/locast2tuner/config
Finally, enable and start the service:

$ sudo systemctl enable locast2tuner
$ sudo systemctl start locast2tuner

and perfect without error, actually i installed Apache 2 that si working perfect, i have disabled iptables and i am trying to used on browser for one PC in the same network http://192.168.1.163:6077

This site can’t be reached192.168.1.163 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

and apache is working fine, also i configured config with my username and password adn like example but alltime report me This site Can't be reached :(

some suggestion?

thank in advance

**Comment by teleflix** [comment]
OK finally is working :) i am getting tuner.m3u but now i am getting one issues uhmmm i mean using stream direct on VLC local works perfect and using since using since one iptv panel inside US  to my this PC inside works fine but since my other iptv load balance that is in canada no work uhmm is detecting geolocalization from my load balance? wear if use my laod balance here near where i am works fine.

some suggestion?

**Comment by teleflix** [comment]
well Finally is working :), but is wear works for about 10 seconds, after use sudo systemctl start locast2tuner report me a list of .m3u i use on vlc and works for about 10 or 20 seconds, when i i refresh or F5 to tiner.m3u report  This site can't be reached :( but i fi run a sudo systemctl start locast2tuner commans will be works again for 10 or 20 seconds again :(

soem suggestion?

**Comment by wouterdebie** [comment]
What URL do you give to VLC?

**Comment by wouterdebie** [comment]
And could you provide some logs from locast2tuner?

**Comment by wouterdebie** [comment]
I'm closing this issue, given the quality of the feedback is low. I've added an issue template for bugs that should be used to give us as much data about the issue as possible.
