### ISSUE TITLE
channels on xtream-ui local

### ISSUE THREAD

**Issue by teleflix** [wouterdebie/locast2tuner#65]
Hello

guys i installed perfect and i am getting stream 6077/tuner.m3u,, now i installed the script in one server and the same time i have installed Xtream-Ui iptv panel  and i used one stream on panel and works :) but only work one channels jejeje, testing the rest of stream all report DOWN but if i test the stream that report down on VLC player works perfect. some suggestion?

my configuration is Ubuntu 18.04 with locast2tuner and Xtream-ui iptv panel and only is working one channels and the rest of channels report Down, but if i use in my pc using VLC all stream are working fine :(

some idea for fix it?

thank in advance

**Comment by wouterdebie** [comment]
Would you mind filing a proper issue? Logs, config, screenshot?
