### ISSUE TITLE
Help with Synology Docker Install

### ISSUE THREAD

**Issue by hdmllr** [wouterdebie/locast2tuner#66]
While I have been able to get locast2tuner up and running on a windows linux machine, I am struggling to get it to launch via docker on a synology server.  It fails on the login, so I think I am not mapping the config file correctly when I am launching it with the docker interface.  Can anyone advise on the mount path that I should be using to map the physical config file to the container?

**Comment by eiddor** [comment]
The app is going to look for the file `/app/config/config`, so you want to map whatever your local directory is to `/app/config/`

**Comment by hdmllr** [comment]
Thanks eiddor.  This is the mount path that I was trying.  I guess it is something else.   I'll double-check that I have the config file set-up correctly.

**Comment by eiddor** [comment]
See if you can grab a log from the container and we might be able to narrow it down.

**Comment by hdmllr** [comment]
![2021-07-18](https://user-images.githubusercontent.com/67057831/126080259-fb284dda-53e8-41a0-8b11-c36d629fb417.png)

**Comment by eiddor** [comment]
Looks like the config file itself is the problem, but I'm not 100% sure.  If you moved your windows config file over then you may have to remove the CR/LFs.  It might be easier to build it from scratch or start with the default one and edit it.

**Comment by hdmllr** [comment]
Thanks for the suggestion.  I'll try to build it from scratch as I am only using a few parameters.
