### ISSUE TITLE
Channels-DVR compatibility

### ISSUE THREAD

**Issue by johnluber** [wouterdebie/locast2tuner#67]
First, awesome program!  Works very well and great documentation to get it up and running...

Not sure how many of your users use this along side of Channels-DVR but it has been mentioned in their forums at least once or twice.  

I set it up today using multiple zip codes and multiplexing and ran into an issue where they require an m3u tag of 'channel-id' in order to be able to uniquely identify every channel.  Your M3u doesn't output that tag.

I was able to work around it by saving the m3u as a file and changing 'tvg-id' to be 'channel-id'.

I'd prefer not to have a file based m3u so was wondering if you would consider adding 'channel-id' to the m3u?

**Comment by wouterdebie** [comment]
I've just pushed 0.1.44 (which should be available in 15 mins or so after it's built) that should have this addition. Let me know if this works.

**Comment by johnluber** [comment]
Wow, that was very quick!  Yes, I updated and it does seem to work just fine.  If I see anything different I'll let you know, but from I see it should not have problems.

Thanks so much!

**Comment by wouterdebie** [comment]
@johnluber Thanks for the reply! And thanks for the feedback!
