### ISSUE TITLE
Update valid zip codes and cities in assets

### ISSUE THREAD

**Issue by gedster314** [wouterdebie/locast2tuner#68]
Can we get an updated zip code/city list.  Also it would be nice to get the zip codes in the config file updated.  

At the time of this request, there were 36 cities.  Here is what is working on my current setup.

98101, Seattle, WA
94102, San Francisco, CA
90210, Los Angeles, CA
85006, Phoenix, AZ
80019, Denver, CO
57701, Rapid City, SD
57103, Sioux Falls, SD
51054, Sioux City, IA
55111, Minneapolis, MN
75001, Dallas, TX
77002, Houston, TX
60601, Chicago, IL
46077, Indianapolis, IN
30301, Atlanta, GA
33602, Tampa, FL
33125, Miami, FL
33403, Palm Beach, FL
20002, Washington, DC
21206, Baltimore, MD
19103, Philadelphia, PA
18505, Scranton, PA
10009, New York, NY
02115, Boston, MA
53558, Madison, WA
32789, Orlando, FL
28102, Charlotte, NC
95605, Sacramento, CA
44102, Cleveland, OH
43016, Columbus, OH
48201, Detroit, MI
53202, Milwaukee, WI
97086, Portland OR
00909, Puerto Rico
27545, Raleigh NC
37660, Tri-Cities TN
15120, Pttsburgh PA

Thanks

**Comment by eiddor** [comment]
PR submitted - thanks for the issue!

**Comment by gedster314** [comment]
Try connecting before officially before updating.  I think I clip boarded from list with one bad zip code, think it was Houston.  If you want when I get home I can clip board it from the log file.

**Comment by eiddor** [comment]
@gedster314 If you could test it, I'd appreciate it - I don't really have an easy way to do that right now.  

Does Locast publish the list anywhere?

**Comment by gedster314** [comment]
Yes, on their page under guide or cities.   No zips though.  I just added to the list of 22 zips in the config file by googling the zips for the new cities and plugging them in.  When ever I get a press release of a new city I add it.On Aug 1, 2021 8:23 AM, Roddie Hasan ***@***.***> wrote:
@gedster314 If you could test it, I'd appreciate it - I don't really have an easy way to do that right now.
Does Locast publish the list anywhere?

**Comment by gedster314** [comment]
I'll post the related part of my log file in a bit and double check the zips.

**Comment by eiddor** [comment]
Ahhh - Maybe what I'll do is add a URL to those files for reference so that users can always get an updated list, and then every once in a while I can update the zip codes when there are a bunch of new cities.

FWIW - Houston's zip code is correct according to Google.

**Comment by gedster314** [comment]
Here is the working config file line:
override_zipcodes=["98101","94102","90210","85006","80019","57701","57103","51054","55111","75001","77002","60018","46077","30301","33602","33125","33403","20002","21206","19103","18505","10009","02115","53558","32789","28102","95605","44102","43016","48201","53202","97086","00909","27545","37660","15120"]

No log file data, it was easier to get it from the command line output.:
 INFO  | Seattle         | 98101
INFO  | San Francisco   | 94102
INFO  | Los Angeles     | 90210
INFO  | Phoenix         | 85006
INFO  | Denver          | 80019
INFO  | Rapid City      | 57701
INFO  | Sioux Falls     | 57103
INFO  | Sioux City      | 51054
INFO  | Minneapolis     | 55111
INFO  | Dallas          | 75001
INFO  | Houston         | 77002
INFO  | Chicago         | 60018
INFO  | Indianapolis    | 46077
INFO  | Atlanta         | 30301
INFO  | Tampa Bay       | 33602
INFO  | Miami           | 33125
INFO  | West Palm Beach | 33403
INFO  | Washington DC   | 20002
INFO  | Baltimore       | 21206
INFO  | Philadelphia    | 19103
INFO  | Scranton        | 18505
INFO  | New York        | 10009
INFO  | Boston          | 02115
INFO  | Madison         | 53558
INFO  | Orlando         | 32789
INFO  | Charlotte       | 28102
INFO  | Sacramento      | 95605
INFO  | Cleveland       | 44102
INFO  | Columbus        | 43016
INFO  | Detroit         | 48201
INFO  | Milwaukee       | 53202
INFO  | Portland        | 97086
INFO  | Puerto Rico     | 00909
INFO  | Raleigh         | 27545
INFO  | Tri-Cities      | 37660    
INFO  | Pittsburgh      | 15120

**Comment by eiddor** [comment]
Yeah, I've never used the override function, but I imagine passing every zip code is going to be a lot.  As I mentioned, they're only provided in those files as a reference.

There were only three difference between what I already had, so I'm updating those and pushing.  I'm also including a reference to the actual Locast page:

`# Please see https://www.locast.org/dma for a current map of the supported regions`

**Comment by gedster314** [comment]
I use the overide even with one zip code because I'm using an At&t hotspot and sometimes At&t will give me a Phoenix ip address which gets me Phoenix Locast channels.  Visible use to route my traffic to a mid-west server that was not a Locast location.

**Comment by eiddor** [comment]
Makes sense, I think one zip code is the intended use - Honestly I've only ever used Locast to help with this project, so I don't have a ton of experience with the options here.

PR has been update - I appreciate you opening the issue!

**Comment by wouterdebie** [comment]
I just merged the PR
