### ISSUE TITLE
Changelog or Version History? Notifications on new versions of locast2tuner?

### ISSUE THREAD

**Issue by sumocomputers** [wouterdebie/locast2tuner#74]
This is probably my ignorance on how Github works, but is there a place that shows a Changelog or Version History?

Also, if I wanted to be notified of new versions of locast2tuner, what would be the best way to do that?

Right now I just look at the main "code" page and see if there is a new version for Cargo.lock or Cargo.toml, but figured there is a better way.

**Comment by eiddor** [comment]
> This is probably my ignorance on how Github works, but is there a place that shows a Changelog or Version History?

Changelog/version history is mostly handled per-project, but on a project's main page you can see when the last commit was made up at the top:

![image](https://user-images.githubusercontent.com/7586731/128551342-eb2d0520-38df-4505-9e26-341b7da63a7d.png)

You can also click release over on the right to see the list of releases:

![image](https://user-images.githubusercontent.com/7586731/128551406-c7b821aa-1b4c-45aa-93a7-bb9d19478a57.png)

> Also, if I wanted to be notified of new versions of locast2tuner, what would be the best way to do that?

At the top right of the screen click "Watch" and you can select what kind of notifications you receive.  

![image](https://user-images.githubusercontent.com/7586731/128551573-937499c9-2dcc-4d27-a7c9-39d3863e1b39.png)

Depending on the project size I generally want all notifications (issues, commits, releases, etc.), but you can pick and choose.

**Comment by sumocomputers** [comment]
Hey Roddie,

Thanks so much for helping a newbie. This is exactly what I was looking for!

Chris
