### ISSUE TITLE
Errors from Docker (missing field 'transcodeId')

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2tuner#80]
**Describe the bug**
When the Docker container starts, getting a "panic" error from Locast2Tuner.  Keeps restarting endlessly.  My container was working fine till this morning.

**To Reproduce**
1. Run the Docker container.
2. Error message occurs and restarts.

** Logs **
Sorry for the weird control characters, this is what's getting saved to the log file from Docker.  Here's two rotations of the logs, showing that it keeps restarting.

stdoutÌ–»ÎÁÒôÍ%config selected = /app/config/config    9   s
stderr˜…ÃÑÁÒôÍ_Aug 16 15:20:23.760 INFO locast2tuner 0.1.48 on Linux 5.4.72-microsoft-standard-WSL2 starting..   s   W
stderrèÍ­ÒÁÒôÍCAug 16 15:20:23.762 INFO UUID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx   W   Q
stderr”òŽÓÁÒôÍ=Aug 16 15:20:23.764 INFO Logging in with someone@xxxyyyzzz.com   Q   =
stderr´ª®ÃÒôÍ)Aug 16 15:20:24.223 INFO Login succeeded!   =   j
stderrÒ˜ÌÅÒôÍVAug 16 15:20:24.823 INFO Using cached FCC facilities at /root/.locast2tuner/facilities   j   ß
stderrØû÷ËÖÒôÍÊthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `transcodeId`", line: 1, column: 227762) }', src/service/mod.rs:329:10   ß   a
stderr¸´®ÌÖÒôÍMnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace   a   9
stdout ÓºÙÒôÍ%config selected = /app/config/config    9   s
stderr¬®¼“ÙÒôÍ_Aug 16 15:20:30.072 INFO locast2tuner 0.1.48 on Linux 5.4.72-microsoft-standard-WSL2 starting..   s   W
stderr¼ý¨”ÙÒôÍCAug 16 15:20:30.074 INFO UUID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx   W   Q
stderräÉò”ÙÒôÍ=Aug 16 15:20:30.076 INFO Logging in with someone@xxxyyyzzz.com   Q   =
stderrÀÀÊÛÚÒôÍ)Aug 16 15:20:30.492 INFO Login succeeded!   =   j
stderr¼ÓÝâÜÒôÍVAug 16 15:20:31.044 INFO Using cached FCC facilities at /root/.locast2tuner/facilities   j   ß
stderr´‚¨ïíÒôÍÊthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `transcodeId`", line: 1, column: 227762) }', src/service/mod.rs:329:10   ß   a
stderr¸¿¯ïíÒôÍMnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace   a   9

** Configuration **
Can't get the config from the web interface as it doesn't keep running long enough.

**Environment**
Docker under Windows 10

**Screenshots**
N/A

** Environment**
Windows 10

**Comment by Croq360** [comment]
Oh, just saw new version.  Let me try that out and will close if it's addressed.  Seems to reference exactly what I'm seeing.

**Comment by wouterdebie** [comment]
Yeah, this is fixed in 0.1.53

**Comment by Croq360** [comment]
Odd, trying to build new version after "pull" with docker-compose, and it's hanging up.

**Comment by wouterdebie** [comment]
@eiddor might know :D

**Comment by eiddor** [comment]
@Croq360 No issues here:

```
roddie@plex ~/docker% docker-compose pull
Pulling plex         ... done
Pulling locast2tuner ... done
roddie@plex ~/docker% docker-compose up -d
Recreating locast2tuner ... 
Recreating locast2tuner ... done
```

Try to pull again.

**Comment by Croq360** [comment]
I removed my previous container, but here's what I get (note that the Error statement is from me hitting Ctrl-C):

C:\Croq360\locast2tuner-Docker>docker-compose pull
Pulling locast2tuner ... done

C:\Croq360\locast2tuner-Docker>docker-compose up -d
Creating locast2tuner ...
ERROR: Aborting.

And this worked fine before.  And "docker run" command (with updating my /app/config path) works too.

**Comment by Croq360** [comment]
Oh, and I deleted all the images in Docker before re-pulling, just in case.

**Comment by eiddor** [comment]
Try this:

Stop the container (it's probably already stopped).

Run: `docker system prune -a -f`

And then do a `docker-compose pull` and `docker-compose up` (don't use `-d` for this so we can see what's going on).

I'm in Glitter now if you want to work on this.

**Comment by Croq360** [comment]
C:\Croq360\locast2tuner-Docker>docker system prune -a -f
Deleted Networks:
locast2tuner-docker_default

Total reclaimed space: 0B

C:\Croq360\locast2tuner-Docker>docker-compose pull
Pulling locast2tuner ... done

C:\Croq360\locast2tuner-Docker>docker-compose up
Creating network "locast2tuner-docker_default" with the default driver
Creating locast2tuner ...

******* And just stays on that last line.  Never seems to finish.

**Comment by wouterdebie** [comment]
can you try `docker-compose --verbose up`?

**Comment by eiddor** [comment]
Just tried updating/starting on a Windows box and it works fine there, as well.

Have you checked to see if Docker has an update?

![image](https://user-images.githubusercontent.com/7586731/129594937-d95298bc-e38c-4590-902f-031c756a8257.png)

**Comment by Croq360** [comment]
No updates showing for docker-desktop.

**Comment by Croq360** [comment]
`C:\Croq360\locast2tuner-Docker>docker-compose --verbose up
compose.config.config.find: Using configuration files: .\docker-compose.yml
compose.cli.docker_client.get_client: docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
compose.cli.docker_client.get_client: Docker base_url: http+docker://localnpipe
compose.cli.docker_client.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '20.10.7', 'Details': {'ApiVersion': '1.41', 'Arch': 'amd64', 'BuildTime': '2021-06-02T11:54:58.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'b0f5bc3', 'GoVersion': 'go1.13.15', 'KernelVersion': '5.4.72-microsoft-standard-WSL2', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.4.6', 'Details': {'GitCommit': 'd71fcd7d8303cbf684402823e425e9dd2e99285d'}}, {'Name': 'runc', 'Version': '1.0.0-rc95', 'Details': {'GitCommit': 'b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7'}}, {'Name': 'docker-init', 'Version': '0.19.0', 'Details': {'GitCommit': 'de40ad0'}}], Version=20.10.7, ApiVersion=1.41, MinAPIVersion=1.12, GitCommit=b0f5bc3, GoVersion=go1.13.15, Os=linux, Arch=amd64, KernelVersion=5.4.72-microsoft-standard-WSL2, BuildTime=2021-06-02T11:54:58.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('locast2tunerdocker_default')
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
compose.cli.verbose_proxy.proxy_callable: docker info -> {'Architecture': 'x86_64',
 'BridgeNfIp6tables': True,
 'BridgeNfIptables': True,
 'CPUSet': True,
 'CPUShares': True,
 'CgroupDriver': 'cgroupfs',
 'CgroupVersion': '1',
 'ContainerdCommit': {'Expected': 'd71fcd7d8303cbf684402823e425e9dd2e99285d',
                      'ID': 'd71fcd7d8303cbf684402823e425e9dd2e99285d'},
 'Containers': 0,
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('locast2tuner-docker_default')
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {'Attachable': True,
 'ConfigFrom': {'Network': ''},
 'ConfigOnly': False,
 'Containers': {},
 'Created': '2021-08-16T16:04:30.7074347Z',
 'Driver': 'bridge',
 'EnableIPv6': False,
 'IPAM': {'Config': [{'Gateway': '172.18.0.1', 'Subnet': '172.18.0.0/16'}],
          'Driver': 'default',
          'Options': None},
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=locast2tuner-docker', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=locast2tunerdocker', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tuner-docker', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tunerdocker', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tuner-docker', 'com.docker.compose.service=locast2tuner', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tunerdocker', 'com.docker.compose.service=locast2tuner', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('ghcr.io/wouterdebie/locast2tuner:latest')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': 'buildkit.dockerfile.v0',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['/locast2tuner',
                           '--config',
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tuner-docker', 'com.docker.compose.service=locast2tuner', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tunerdocker', 'com.docker.compose.service=locast2tuner', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: {<Service: locast2tuner>}
compose.parallel.feed_queue: Starting producer thread for <Service: locast2tuner>
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tuner-docker', 'com.docker.compose.service=locast2tuner', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=locast2tunerdocker', 'com.docker.compose.service=locast2tuner', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
Creating locast2tuner ...
compose.parallel.feed_queue: Pending: {ServiceName(project='locast2tuner-docker', service='locast2tuner', number=1)}
compose.parallel.feed_queue: Starting producer thread for ServiceName(project='locast2tuner-docker', service='locast2tuner', number=1)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('ghcr.io/wouterdebie/locast2tuner:latest')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': 'buildkit.dockerfile.v0',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['/locast2tuner',
                           '--config',
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('ghcr.io/wouterdebie/locast2tuner:latest')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': 'buildkit.dockerfile.v0',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['/locast2tuner',
                           '--config',
...
compose.service.build_container_labels: Added config hash: 47cb8e425903c4e369c2724ed5a856a7387f46eaeeddb9915ae9974afbeb7641
compose.cli.verbose_proxy.proxy_callable: docker create_host_config <- (links=[], port_bindings={'6077/tcp': ['6077']}, binds=['C:\\Users\\Croq360\\.locast2tuner:/app/config:rw'], volumes_from=[], privileged=False, network_mode='locast2tuner-docker_default', devices=None, device_requests=None, dns=None, dns_opt=None, dns_search=None, restart_policy={'Name': 'unless-stopped', 'MaximumRetryCount': 0}, runtime=None, cap_add=None, cap_drop=None, mem_limit=None, mem_reservation=None, memswap_limit=None, ulimits=None, log_config={'Type': 'local', 'Config': {'max-file': 10, 'max-size': '10m'}}, extra_hosts=None, read_only=None, pid_mode=None, security_opt=None, ipc_mode=None, cgroup_parent=None, cpu_quota=None, shm_size=None, sysctls=None, pids_limit=None, tmpfs=None, oom_kill_disable=None, oom_score_adj=None, mem_swappiness=None, group_add=None, userns_mode=None, init=None, init_path=None, isolation=None, cpu_count=None, cpu_percent=None, nano_cpus=None, volume_driver=None, cpuset_cpus=None, cpu_shares=None, storage_opt=None, blkio_weight=None, blkio_weight_device=None, device_read_bps=None, device_read_iops=None, device_write_bps=None, device_write_iops=None, mounts=None, device_cgroup_rules=None, cpu_period=None, cpu_rt_period=None, cpu_rt_runtime=None)
compose.cli.verbose_proxy.proxy_callable: docker create_host_config -> {'Binds': ['C:\\Users\\Croq360\\.locast2tuner:/app/config:rw'],
 'Links': [],
 'LogConfig': {'Config': {'max-file': 10, 'max-size': '10m'}, 'Type': 'local'},
 'NetworkMode': 'locast2tuner-docker_default',
 'PortBindings': {'6077/tcp': [{'HostIp': '', 'HostPort': '6077'}]},
 'RestartPolicy': {'MaximumRetryCount': 0, 'Name': 'unless-stopped'},
 'VolumesFrom': []}
compose.cli.verbose_proxy.proxy_callable: docker create_container <- (image='ghcr.io/wouterdebie/locast2tuner:latest', ports=[('6077', 'tcp')], volumes={'/app/config': {}}, name='locast2tuner', detach=True, environment=[], labels={'com.docker.compose.project': 'locast2tuner-docker', 'com.docker.compose.service': 'locast2tuner', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project.working_dir': 'C:\\Croq\\locast2tuner-Docker', 'com.docker.compose.project.config_files': 'docker-compose.yml', 'com.docker.compose.container-number': '1', 'com.docker.compose.version': '1.29.2', 'com.docker.compose.config-hash': '47cb8e425903c4e369c2724ed5a856a7387f46eaeeddb9915ae9974afbeb7641'}, host_config={'NetworkMode': 'locast2tuner-docker_default', 'RestartPolicy': {'Name': 'unless-stopped', 'MaximumRetryCount': 0}, 'VolumesFrom': [], 'Binds': ['C:\\Users\\Croq360\\.locast2tuner:/app/config:rw'], 'PortBindings': {'6077/tcp': [{'HostIp': '', 'HostPort': '6077'}]}, 'Links': [], 'LogConfig': {'Type': 'local', 'Config': {'max-file': 10, 'max-size': '10m'}}}, networking_config={'EndpointsConfig': {'locast2tuner-docker_default': {'Aliases': ['locast2tuner'], 'IPAMConfig': {}}}})
compose.parallel.feed_queue: Pending: set()`

**Comment by Croq360** [comment]
That "Pending: set()" just keeps streaming out, over and over.

**Comment by Croq360** [comment]
Gonna try a restart - can't hurt I guess...

If I can't get this working, I'll go back to building it manually and running as a service for the time being.

Unless there's a way to pull a Windows executable (which would be much easier of course).

**Comment by eiddor** [comment]
Yeah, that's weird - Try a reboot (or restart Docker) and let us know.

Found this, but it's not very helpful: https://github.com/docker/compose/issues/7577

**Comment by wouterdebie** [comment]
Does this help? https://github.com/docker/compose/issues/7577

**Comment by Croq360** [comment]
In case I decide to punt on Docker (for now anyway), is there a Windows executable maintained somewhere that I can just download, or do I need to pull the code over and compile it myself?

**Comment by eiddor** [comment]
You said that `docker run` works, right?  I would just use that for now vs. going the service route.

**Comment by wouterdebie** [comment]
There's no windows binary being built right now..

**Comment by Croq360** [comment]
Yeah, I've got some logging settings going for Docker that does rotating log files, so that it doesn't get excessively huge.  Will have to read the docs on how to get that configured on the command line.

**Comment by eiddor** [comment]
Paste your `docker-compose.yml` file here - it's pretty easy to translate.

**Comment by Croq360** [comment]
`version: '3'
services:
  locast2tuner:
    image: ghcr.io/wouterdebie/locast2tuner:latest
    container_name: locast2tuner
    volumes:
      - C:/Users/Croq360/.locast2tuner:/app/config
    ports:
      - 6077:6077
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-file: 10
        max-size: 10m
`

**Comment by Croq360** [comment]
I figured out the "restart" one.  Looks like I can maybe use "--logging-driver local -log-opt max-file=10 -log-opt max-size=10m" for the logging?

**Comment by eiddor** [comment]
`docker run -p 6077:6077 -v C:\Users\Croq360\.locast2tuner:/app/config -name locast2tuner -d --restart unless-stopped --log-driver local --log-opt max-file=10 --log-opt max-size=10m ghcr.io/wouterdebie/locast2tuner:latest`

**Comment by Croq360** [comment]
This worked for me.  Changed "-p" to "--publish", "-v" to "--volume", and "-name" to "--name".

`docker run --publish 6077:6077 --volume C:\Users\Croq360\.locast2tuner:/app/config --name locast2tuner -d --restart unless-stopped --log-driver local --log-opt max-file=10 --log-opt max-size=10m ghcr.io/wouterdebie/locast2tuner:latest`

**Comment by eiddor** [comment]
Windows. 🙄 

So, the only difference between that CLI and your YAML file is that I used backslashes for the Windows side of the volume instead of forward slashes.  Try changing those in your `docker-compose.yml`

```
    volumes:
      - C:\Users\Croq360\.locast2tuner:/app/config
```

**Comment by Croq360** [comment]
I can give it a try, but forward slashes in the YAML file were working before with no issues.

**Comment by eiddor** [comment]
I know - Just guessing, as this is the only difference.

If that doesn't work, then I'm not sure what to think.

**Comment by Croq360** [comment]
As I suspected, no go with either forward or backward slashes.  Oh well, at least I can do "docker run".  Saved it to a batch file in the same folder where I have docker-compose.

**Comment by Croq360** [comment]
I guess we can close this now since I've got it working (though weirdly, the docker-compose thing no longer is working for me).  Thanks for the help!
