### ISSUE TITLE
Repository gone??

### ISSUE THREAD

**Issue by slikone27** [wouterdebie/locast2tuner#84]
Trying to start this container for unraid but it appears the repo is gone?

https://registry.hub.docker.com/r/wouterdebie/locast2tuner

404 error

**Comment by wouterdebie** [comment]
Not sure where you got this from.. I never published to dockerhub.

**Comment by wouterdebie** [comment]
https://github.com/RandomNinjaAtk/unraid-templates/commit/3c55aaac1ebe484f4b17e34efd3bacee263e2e7c Might have something to do with this though, but I don't maintain that.

**Comment by slikone27** [comment]
Thanks... just noticed that.  Changing the repo field to: ghcr.io/wouterdebie/locast2tuner-unraid:latest seemed to do the trick and now it is working.  does using multiple zip codes pull channels from those markets as well?

**Comment by RandomNinjaAtk** [comment]
> Thanks... just noticed that. Changing the repo field to: ghcr.io/wouterdebie/locast2tuner-unraid:latest seemed to do the trick and now it is working. does using multiple zip codes pull channels from those markets as well?

yes it does

**Comment by slikone27** [comment]
> > Thanks... just noticed that. Changing the repo field to: ghcr.io/wouterdebie/locast2tuner-unraid:latest seemed to do the trick and now it is working. does using multiple zip codes pull channels from those markets as well?
> 
> yes it does

Thanks!  Should I have changed the repo in your unraid container to make it work?  not sure why it threw the error that it was trying to pull from docker and couldn't find it.

For multi-region if I use multiple zip codes... can i get a channel say CBS in both markets to watch live sports from both?

**Comment by wouterdebie** [comment]
> For multi-region if I use multiple zip codes... can i get a channel say CBS in both markets to watch live sports from both?

yes you can.. somewhat off topic for this thread, so I'll close this issue.. If you want user help, please don't hesitate to join us on Gitter
