### ISSUE TITLE
Multiple zip codes (multiplexing not working) after update from v0.2.9 to v0.3.0; Unraid custom IP also no longer working

### ISSUE THREAD

**Issue by dwilson1251** [wouterdebie/locast2tuner#90]
UNRAID - Docker

No changes to config, multiplexing seems to have stopped working from 0.2.9 to 0.3.0; see logs below.  Also, just noticed that beginning w/v0.2.0 the container no longer respects a custome ip (br0) in Unraid.  This is an issue becasue my plex container uses a custom ip and can't be routed to from either the internal default bridge or a custom one.

Multiplexing and Remap = true

Realize this isn't the bug template but figured logs would be more specific

`v0.3.0 - Log Results

Aug 22 01:03:55.427 INFO locast2tuner 0.3.0 on Linux 5.10.28-Unraid starting..
Aug 22 01:03:55.428 INFO UUID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Aug 22 01:03:55.428 INFO Logging in with XXXXXXXXXXXXXXXXXXXXXXXXXXX
Aug 22 01:03:55.577 INFO Login succeeded!
Aug 22 01:03:55.861 INFO Downloading FCC facilities
Aug 22 01:03:56.409 INFO Cached FCC facilities to /root/.locast2tuner/facilities
Aug 22 01:03:56.922 INFO Loading stations for Washington DC (cache: true, cache timeout: 3600, days: 8)..
Aug 22 01:03:56.930 WARN Channels will be remapped!
Aug 22 01:03:56.930 INFO Starting http server for Multiplexer on http://0.0.0.0:6077
Aug 22 01:03:56.930 INFO Starting 32 workers
Aug 22 01:03:56.934 INFO Starting "actix-web-service-0.0.0.0:6077" service on 0.0.0.0:6077
Aug 22 01:03:56.934 INFO Tuners:
Aug 22 01:03:56.935 INFO +---------------+----------+-----+--------------------------------------+------------------+
Aug 22 01:03:56.935 INFO | City | Zip code | DMA | UUID | Timezone |
Aug 22 01:03:56.935 INFO +---------------+----------+-----+--------------------------------------+------------------+
Aug 22 01:03:56.935 INFO | Washington DC | 20105 | 511 | e80b8e77-54ef-57af-a13d-edd2a0e8daba | America/New_York |
Aug 22 01:03:56.935 INFO +---------------+----------+-----+--------------------------------------+------------------+
Aug 22 01:03:56.935 INFO Multiplexer:
Aug 22 01:03:56.935 INFO +--------------------------------------+---------------------+
Aug 22 01:03:56.935 INFO | UID | URL |
Aug 22 01:03:56.935 INFO +--------------------------------------+---------------------+
Aug 22 01:03:56.935 INFO | 788992e7-c4e8-4fe6-95a5-6bbcf45e5c76 | http://0.0.0.0:6077 |
Aug 22 01:03:56.935 INFO +--------------------------------------+---------------------+
Aug 22 01:03:56.935 INFO
Aug 22 01:03:56.935 INFO locast2tuner started..

v0.2.9 - Log Results
Aug 22 01:07:23.618 INFO locast2tuner 0.2.9 on Linux 5.10.28-Unraid starting..
Aug 22 01:07:23.618 INFO UUID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Aug 22 01:07:23.618 INFO Logging in with XXXXXXXXXXXXXXXXXXXXXXXXXXX
Aug 22 01:07:23.845 INFO Login succeeded!
Aug 22 01:07:24.089 INFO Downloading FCC facilities
Aug 22 01:07:24.429 INFO Cached FCC facilities to /root/.locast2tuner/facilities
Aug 22 01:07:25.131 INFO Loading stations for Washington DC (cache: true, cache timeout: 3600, days: 8)..
Aug 22 01:07:25.391 INFO Loading stations for San Francisco (cache: true, cache timeout: 3600, days: 8)..
Aug 22 01:07:25.401 WARN Channels will be remapped!
Aug 22 01:07:25.402 INFO Starting http server for Multiplexer on http://0.0.0.0:6077
Aug 22 01:07:25.402 INFO Starting 32 workers
Aug 22 01:07:25.406 INFO Starting "actix-web-service-0.0.0.0:6077" service on 0.0.0.0:6077
Aug 22 01:07:25.406 INFO Tuners:
Aug 22 01:07:25.407 INFO +---------------+----------+-----+--------------------------------------+---------------------+
Aug 22 01:07:25.407 INFO | City | Zip code | DMA | UUID | Timezone |
Aug 22 01:07:25.407 INFO +---------------+----------+-----+--------------------------------------+---------------------+
Aug 22 01:07:25.407 INFO | Washington DC | 20105 | 511 | d96f4c86-6ebf-51da-b3d9-f9c9a43668bb | America/New_York |
Aug 22 01:07:25.407 INFO | San Francisco | 95116 | 807 | 79402a65-dbe3-5fdf-91f2-17d41f1c9f31 | America/Los_Angeles |
Aug 22 01:07:25.407 INFO +---------------+----------+-----+--------------------------------------+---------------------+
Aug 22 01:07:25.407 INFO
Aug 22 01:07:25.407 INFO Multiplexer:
Aug 22 01:07:25.407 INFO +--------------------------------------+---------------------+
Aug 22 01:07:25.407 INFO | UID | URL |
Aug 22 01:07:25.407 INFO +--------------------------------------+---------------------+
Aug 22 01:07:25.407 INFO | 1dd79d0c-2c8a-4735-b679-14d4487ecadd | http://0.0.0.0:6077 |
Aug 22 01:07:25.407 INFO +--------------------------------------+---------------------+
Aug 22 01:07:25.407 INFO locast2tuner started..`

**Comment by wouterdebie** [comment]
@dwilson1251 would you mind posting your config?

**Comment by eiddor** [comment]
> Also, just noticed that beginning w/v0.2.0 the container no longer respects a custome ip (br0) in Unrai

I'll let @wouterdebie help you with the multiplexing thing, but we recently merged the two Docker images together since they're both doing the same thing now, and both images have always bound to `0.0.0.0` (since most people don't know their container IP and it can change) - Were you overriding it with your config file?

**Comment by wouterdebie** [comment]
Ah, multiplexing isn't broken, but there's an issue with starting multiple instances when using `override_zipcodes`.

**Comment by wouterdebie** [comment]
I found the multiplex issue. Fixed in v0.3.1, which is now building.,

**Comment by dwilson1251** [comment]
Figured out the IP thing; for some reason it wasn't showing as connected anymore in plex, and not showing in the unraid UI like you normally do when you config a br0 and a custom IP.  It turned out to be pingable.  However, I think the issue is with v0.3.0, because on v0.2.9 everything seems to be working as it was.

**Comment by wouterdebie** [comment]
I'm not sure I understand the IP issue.. the docker image was always bound to 0.0.0.0.

**Comment by eiddor** [comment]
> Figured out the IP thing; for some reason it wasn't showing as connected anymore in plex

This seems to be a Plex issue - I have no idea why it does this, but it has done that for a while and things still work.  It makes no sense to me.  There's an issue somewhere open for it.  Nothing with IP binding has changed since the day we created the Docker image(s), though.

**Comment by dwilson1251** [comment]
Yeah, no worries there with the IP; seems to be sorted again.

Appreciate the quick response on the multiplexing issue.  Will check back in later this evening and retest.

**Comment by wouterdebie** [comment]
@dwilson1251 v0.3.1 was just built, so please test it out. Sorry for the inconvenience.

**Comment by dwilson1251** [comment]
@wouterdebie - All set; working in both portainer and unraid environments.  Only, template issue seems to be with unraid; if I didn't add the latest tag it didn't pull the latest.  The instructions in the template don't note this so may cause some confusion.  Portainer automatically adds it if it isn't expicity added or includes an alternate.

Again, very appreciative of everyone's work on this; have a great evening.

**Comment by wouterdebie** [comment]
Good to hear! The unraid template can be found here: https://github.com/RandomNinjaAtk/unraid-templates/blob/master/randomninjaatk/locast2tuner.xml. Maybe the maintainer can improve this? I have no clue how unraid works :)
