### ISSUE TITLE
Tuners limited to 3 - this used to be 4

### ISSUE THREAD

**Issue by dwilson1251** [wouterdebie/locast2tuner#91]
UNRAID - Docker

Not a configurable item, however at somepoint the default/ limit for tuners was reduced from 4 to 3

**Comment by dwilson1251** [comment]
I RTFMed and added - l2t_tuner_count to the config; other issue/bug I reported is still an issue.  However, I do suggest the default be set back to 4 as this is what it was previously.

**Comment by wouterdebie** [comment]
Tuner count is actually 16.. Not sure what the template (that I don't maintain) does..

**Comment by dwilson1251** [comment]
@wouterdebie - apologies about the unraid template issues; wasn't clear about the ownership.  I run your solution in unraid, portainer, and bare metal (arm); family ;-)

Not sure if there is a contribution option; buy you a beer, coffee, etc.  Have a great evening/ rest of your weekend.

**Comment by wouterdebie** [comment]
@dwilson1251 No worries! I don't maintain the unraid template, but the rest is mine :)

Funny enough, I'm in the process of adding a donation thing to this project! I'm planning on donating it all to projects that support women and underprivileged kids in STEM education.

**Comment by dwilson1251** [comment]
@wouterdebie - Count me in

Sorry in advance; you got me looking at the code ;-)  I may be looking at this wrong as I am by no means a modern day dev, but take a look at the following; the config.example indicated a default value of 3 tuners and I'm assuming "(3)" is the default value if it doesn't see a value for <u8>:

https://github.com/wouterdebie/locast2tuner/blob/main/src/config.rs

        conf.tuner_count = cfg
            .grab()
            .arg("tuner_count")
            .env("l2t_tuner_count")
            .conf("tuner_count")
            .t_def::<u8>(3);

**Comment by wouterdebie** [comment]
@dwilson1251 NICE CATCH! Just saying 16 doesn't make it 16 :D Releasing soon!

**Comment by wouterdebie** [comment]
v0.3.2 baking..
